//bibpaper[tandem-straight][H. Kawahara and M. Morise, "Technical foundations of TANDEM-STRAIGHT, a speech analysis, modification and synthesis framework," SADHANA - Academy Proceedings in Engineering Sciences, vol. 36, no. 5 , pp. 713-728, Oct. 2011.]
//bibpaper[prml][C.M. ビショップ, "パターン認識と機械学習," 丸善出版, Apr. 2012.]
//bibpaper[stat-ml][杉山 将, "統計的機械学習―生成モデルに基づくパターン認識," オーム社, Sep. 2009.]
//bibpaper[mfcc-aidiary][http://aidiary.hatenablog.com/entry/20120225/1330179868]
//bibpaper[dtw-ut][亀岡 弘和, "東京大学工学部 講義資料「応用音響学 第5回」", May. 2014. http://hil.t.u-tokyo.ac.jp/~kameoka/aa/AA14_05.pdf]
//bibpaper[toda-traj][T. Toda, A. W. Black, and K. Tokuda, "Voice conversion based on maximum likelihood estimation of spectral parameter trajectory," IEEE Trans. Audio, Speech, Lang. Process, vol. 15, no. 8, pp. 2222–2235, Nov. 2007.]
//bibpaper[r9y9-gmm][http://r9y9.github.io/blog/2014/07/05/statistical-voice-conversion-muzui/]
//bibpaper[evgmm][T. Toda, Y. Ohtani, and K. Shikano, "Eigenvoice conversion based on Gaussian mixture model," Ninth International Conference on Spoken Language Processing. 2006.]
//bibpaper[ref-evgmm][Y. Ohtani, et al. "Many-tomany eigenvoice conversion with reference voice." Proc. INTERSPEECH. 2009.]
